"""Agregar borradores y soporte para múltiples imágenes

Revision ID: 4f87a47f0e53
Revises: 15d329109a87
Create Date: 2025-11-17 10:51:47.431891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f87a47f0e53'
down_revision = '15d329109a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagen_objeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('objeto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['objeto_id'], ['objeto.id_objeto'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objeto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publicado', sa.Boolean(), nullable=True))
        batch_op.alter_column('fecha_publicacion',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objeto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.alter_column('fecha_publicacion',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('publicado')

    op.drop_table('imagen_objeto')
    # ### end Alembic commands ###
